// Generated by CoffeeScript 2.7.0
  // GraphLib.coffee
import {
  scaleLinear
} from 'd3-scale';

export var getScaler = (lData, minOut, maxOut) => {
  var i, len, maxData, minData, n;
  minData = Number.MAX_VALUE;
  maxData = Number.MIN_VALUE;
  for (i = 0, len = lData.length; i < len; i++) {
    n = lData[i];
    if (n < minData) {
      minData = n;
    }
    if (n > maxData) {
      maxData = n;
    }
  }
  return scaleLinear().domain([minData, maxData]).range([minOut, maxOut]);
};

// ---------------------------------------------------------------------------
export var getScalers = (hSeries, width, height) => {};

// ---------------------------------------------------------------------------
export var getPtScaler = (width, height, lPoints) => {
  var xScaler, yScaler;
  xScaler = getScaler(lPoints.map((x) => {
    return x[0];
  }), 0, width);
  yScaler = getScaler(lPoints.map((x) => {
    return x[1];
  }), height, 0);
  return (pt) => {
    return [xScaler(pt[0]), yScaler(pt[1])];
  };
};

// ---------------------------------------------------------------------------
export var getScaledPoints = (lPoints, scaler) => {
  var i, lScaled, len, pt;
  lScaled = [];
  for (i = 0, len = lPoints.length; i < len; i++) {
    pt = lPoints[i];
    lScaled.push(scaler(pt));
  }
  return lScaled;
};
