// Generated by CoffeeScript 2.7.0
// translatePreProcessor.coffee
import MagicString from 'magic-string';

// ---------------------------------------------------------------------------
export var translatePreProcessor = () => {
  return {
    markup: function({content, filename}) {
      var s;
      s = new MagicString(content);
      return {
        code: s.toString(),
        map: s.generateMap({
          hires: true,
          file: filename
        })
      };
    }
  };
};
